name: Deploy backend to Fly.io
on:
push:
branches:
  - 0ptim/fly-action
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  name: Deployment
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
