name: Label Check

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels
        run: |
          issue_labels_raw=$(jq '.issue.labels | .[].name' $GITHUB_EVENT_PATH | tr -d '"')
          IFS=$'\n' read -rd '' -a issue_labels <<< "$issue_labels_raw"

          for label in "${issue_labels[@]}"; do
            if [[ $label == area:* ]]; then
              has_area_label="true"
              break
            fi
          done

          if [ "$has_area_label" != "true" ]; then
            echo "Error: This issue must have at least one 'area:' label."
            exit 1
          fi
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
