name: Apply supabase migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Apply supabase migrations
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PROJECT_ID: cofmxsabxteiidryklyg

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID
        working-directory: data
      - run: supabase db push
        working-directory: data
