name: Supabase Staging

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy:
    name: Migrate staging database
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      PROJECT_ID: ${{ vars.STAGING_SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID
        working-directory: data
      - run: supabase db push
        working-directory: data
