name: Apply supabase migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  DeployStaging:
    name: Staging migration
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://supabase.com/dashboard/project/iajfqvpslzrtmvekqwpv"

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID
        working-directory: data
      - run: supabase db push
        working-directory: data

  DeployProduction:
    name: Production migration
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://supabase.com/dashboard/project/cofmxsabxteiidryklyg"
    needs: DeployStaging

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID
        working-directory: data
      - run: supabase db push
        working-directory: data
