name: Wiki scraping Staging

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./job

      - name: Run the script
        run: python ./job/app.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ vars.STAGING_SUPABASE_API_URL }}
          SUPABASE_KEY: ${{ secrets.STAGING_SUPABASE_API_ANON_KEY }}
